FROM node:22-alpine AS builder
WORKDIR /home/node
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /home/node
COPY --from=builder /home/node/build ./build
COPY package.json .
EXPOSE 3000
CMD [ "npm", "run", "start" ]

